[package]
name = "odbc_derive"
version = "0.1.0"
authors = ["Marin Veršić <marin.versic101@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1"
quote = "^1"
syn = "^1"
