name: odbc-ci
# TODO: Only on PR on master?
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build rs-odbc
      run: cargo build --release

    - name: Run tests for rs-odbc
      run: cargo test --release
