name: odbc-ci

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Build rs-odbc docker image
      run: docker-compose build

    - name: Start rs-odbc docker container
      run: docker-compose up -d

    - name: Build rs-odbc
      run: docker exec -t rs-odbc cargo build --release

    - name: Run tests for rs-odbc
      run: docker exec -t rs-odbc cargo test --release
